name: Deploy Static Site to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: ReimVPN with Images/html
        run: npm ci

      - name: Build Tailwind CSS
        working-directory: ReimVPN with Images/html
        run: npx tailwindcss -i ./assets/css/output.css -o ./assets/css/main.css --minify

      - name: Prepare Deploy Directory
        run: |
          mkdir deploy
          cp -r "ReimVPN with Images/html"/*.html deploy/ || true
          [ -d "ReimVPN with Images/html/assets" ] && cp -r "ReimVPN with Images/html/assets" deploy/
          [ -d "ReimVPN with Images/html/images" ] && cp -r "ReimVPN with Images/html/images" deploy/
          touch deploy/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          publish_branch: gh-pages
